version: "3.8"
services:
  db:
    image: library/postgres:13
    environment:
      - POSTGRES_DB=socially
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
